---
version: '3'

services:
  watchtower:
    container_name: watchover
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    command: --schedule "0 0 4 * * *" --cleanup --label-enable
