---
version: '3'

services:
  watchtower:
    container_name: watchover
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    environment:
      -  WATCHTOWER_NOTIFICATIONS=slack
      -  WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=https://hooks.slack.com/services/<url>
      -  WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER=<slack_identifier> \
      -  WATCHTOWER_NOTIFICATION_SLACK_CHANNEL=<channel_name> \
    command: --schedule "0 0 4 * * *" --cleanup --label-enable 
    restart: unless-stopped
