version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm_app
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      #- ./config.json:/app/config/production.json
      - ./data:/data
      - ./config:/etc/letsencrypt
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: ${DB_USER}
      DB_MYSQL_PASSWORD: ${DB_PASSWORD} 
      DB_MYSQL_NAME: ${DB_NAME}
      PGID: 1000
      PUID: 1000
    depends_on:
      - db
    labels:
      - com.centurylinklabs.watchtower.enable=true

  db:
    image: 'jc21/mariadb-aria:latest'
    container_name: npm_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/mysql:/var/lib/mysql
    labels:
      - com.centurylinklabs.watchtower.enable=true

networks:
  default:
    external:
      name: npm-ntwrk
