version: '3.8'

networks:
  monitoring:
    driver: bridge
    
volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
  alertmanager:

services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - monitoring
    labels:
      - com.centurylinklabs.watchtower.enable=true

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    restart: unless-stopped
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro
    devices:
      - /dev/kmsg
    networks:
      - monitoring
    ports:
      - 8080:8080
    labels:
      - com.centurylinklabs.watchtower.enable=true

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
        #- '--storage.tsdb.path=/prometheus'
        #- '--web.console.libraries=/etc/prometheus/console_libraries'
        #- '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    networks:
      - monitoring
    labels:
      - com.centurylinklabs.watchtower.enable=true

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
      #environment:
      #- GF_AUTH_ANONYMOUS_ENABLED=true
      #- GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      #- GF_USERS_DEFAULT_THEME=light
      #- GF_LOG_MODE=console
      #- GF_LOG_LEVEL=critical
      #- GF_PANELS_ENABLE_ALPHA=true
    volumes:
      #- ./configs/grafana/provisioning/dashboards.yml:/etc/grafana/provisioning/dashboards/provisioning-dashboards.yaml:ro
      #- ./configs/grafana/provisioning/datasources.yml:/etc/grafana/provisioning/datasources/provisioning-datasources.yaml:ro
      #- ./dashboards/node-metrics.json:/var/lib/grafana/dashboards/node-metrics.json:ro
      #- ./dashboards/container-metrics.json:/var/lib/grafana/dashboards/container-metrics.json:ro
      #- ./grafana/provisioning/:/etc/grafana/provisioning/
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    networks:
      - monitoring
    labels:
      - com.centurylinklabs.watchtower.enable=true

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    restart: unless-stopped
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    depends_on:
      - grafana
    volumes:
      - alertmanager:/alertmanager
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - 9093:9093
    expose:
      - 9093
    networks:
      - monitoring
    labels:
      - com.centurylinklabs.watchtower.enable=true

