version: "3.7"
services:
  homer:
    image: b4bz/homer
    #To build from source, comment previous line and uncomment below
    #build: .
    container_name: homer
    volumes:
      - ./assets:/www/assets
    ports:
      - 2315:8080
    environment:
      - UID=1000
      - GID=1000
      # Only first time
      #- INIT_ASSETS=1
    restart: unless-stopped
