global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
    - targets: ["node-exporter:9100"]

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

      #remote_write:
      #- url: "<Your Prometheus remote_write endpoint>"
      #basic_auth:
      #username: "<Your Grafana Username>"
      #password: "<Your Grafana API key>"
      #
# Rule files specifies a list of globs. Rules and alerts are read from
# all matching files.
rule_files:
  - /etc/prometheus/rules/*

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - "alertmanager:9093"
